name: 🔒 Security Vulnerability
description: Report a security vulnerability (PRIVATE - use Security tab)
labels: ["security", "priority-high"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ STOP - READ THIS FIRST
        
        **DO NOT report security vulnerabilities in public issues!**
        
        Instead:
        1. Go to the **Security** tab above
        2. Click **"Report a vulnerability"**
        3. Submit your report privately
        
        Or email: security@pm-tools-templates.org
        
        ## Why Private Reporting?
        
        - Protects users while we fix the issue
        - Allows coordinated disclosure
        - Follows responsible disclosure practices
        - Gives us time to prepare fixes
        
        ## What Counts as a Security Issue?
        
        - Real credentials or API keys in templates
        - Personal information exposure
        - Malicious content in templates
        - Vulnerable links or downloads
        - Privacy violations
        - Account takeover possibilities
        
        **Thank you for keeping our community safe!**
        
        Please close this issue and use private reporting instead.
  
  - type: checkboxes
    id: acknowledgment
    attributes:
      label: I understand
      options:
        - label: I will use private security reporting instead of this public issue
          required: true

